### ISSUE TITLE
Integrations ? 

### ISSUE THREAD

**Issue by pkutaj** [mintlify/mintlify#96]
Hi there, 

are there plans to enhance integrations? I would specifically be interested in 

1. Confluence
2. Zendesk Help Center
3. Wordpress
4. Github repos with markdown-based docs

Thanks for the great work! Kind regards, 

Pavol

**Comment by hanywang2** [comment]
> Hi there,
> 
> are there plans to enhance integrations? I would specifically be interested in
> 
> 1. Confluence
> 2. Zendesk Help Center
> 3. Wordpress
> 4. Github repos with markdown-based docs
> 
> Thanks for the great work! Kind regards,
> 
> Pavol

1. Added confluence two days ago!
2. Do you mean documentation hosted by Zendesk or integrations with Zendesk's API?
3. Haven't gotten a lot of requests for Wordpress just yet, but we're on it when it becomes a theme!
4. You can add GitHub repos with markdown using `Add Webpage` right now!

**Comment by pkutaj** [comment]
Hi Han,

awesome job with Confluence and GH!

We are quite heavily utilizing Zendesk Help Center in our Support ops, due
to the integration with Zendesk ticketing systems (ease to link docs to
tickets + out-of-the-box reporting, internal effort to use
Knowledge-centered-support methodology), however this essential use-case
for a support team is disconnected from docs in other siloes (SRE in
confluence, marketing in WP, internal in Gdocs). I've seen this in other
companies, too, maybe ZD HC is worth an investigation.

Cheers,

Pavol

Dňa so 18. 6. 2022, 3:10 Han Wang ***@***.***> napísal(a):
